### ISSUE TITLE
A problem occurred configuring project ':flutter_compass'.

### ISSUE THREAD

**Issue by taothai** [tlserver/flutter_map_location_marker#114]
FAILURE: Build failed with an exception.

```
* What went wrong:
A problem occurred configuring project ':flutter_compass'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
Error: Gradle task assembleDebug failed with exit code 1
```

**Comment by tlserver** [comment]
Hi. Can you provide a detailed reproduce step?

**Comment by taothai** [comment]
> Hi. Can you provide a detailed reproduce step?

thank for my reply 

this show error when update  Gradle to version 8.x 
but down version Gradle to version 7.x  It'work

**Comment by AlceoMazza** [comment]
This is caused by the fact that the package `flutter_compass` is currently unmaintained and has not been updated to support Gradle 8.x.
Issue: https://github.com/hemanthrajv/flutter_compass/issues/104

There are 3 potential pull requests that would fix the issue, but none of them has been merged yet:
- https://github.com/hemanthrajv/flutter_compass/pull/95
- https://github.com/hemanthrajv/flutter_compass/pull/102
- https://github.com/hemanthrajv/flutter_compass/pull/103

To work with Gradle 8.x for the moment you should consider adding a dependency override of one of these pull requests in your `pubspec.yaml`:
```
dependency_overrides:
  flutter_compass: # Uncomment one of the following
    # git: https://github.com/AlceoMazza/flutter_compass.git
    # git: https://github.com/helpisdev/flutter_compass.git
    # git:
    #   url: https://github.com/Hans-Einar/flutter_compass.git
    #   ref: patch-1
```

**Comment by fisforfaheem** [comment]
> > Hi. Can you provide a detailed reproduce step?
> 
> thank for my reply 
> 
> this show error when update  Gradle to version 8.x 
> but down version Gradle to version 7.x  It'work
> 

Kindly make a fork and merge the pr and use that instead
