### ISSUE TITLE
Resolving dependencies... issues

### ISSUE THREAD

**Issue by fisforfaheem** [tlserver/flutter_map_location_marker#117]
Resolving dependencies...
Because flutter_map_location_marker 8.0.8 depends on geolocator ^11.0.0 and no versions of flutter_map_location_marker match >8.0.8 <9.0.0, flutter_map_location_marker ^8.0.8 requires geolocator ^11.0.0.
So, because beboro depends on both geolocator ^12.0.0 and flutter_map_location_marker ^8.0.8, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on geolocator: flutter pub add geolocator:^11.1.0
exit code 1

**Comment by fisforfaheem** [comment]
yes, it wont fix, it

**Comment by tlserver** [comment]
Can you share your `pubspec.yaml`? Also, you can try [dependency_override](https://dart.dev/tools/pub/dependencies#dependency-overrides).

**Comment by olavurs** [comment]
Same issue here. Cannot upgrade Geolocator package because of dependency:

Resolving dependencies...
Because flutter_map_location_marker 8.0.8 depends on geolocator ^11.0.0 and no versions of flutter_map_location_marker match >8.0.8 <9.0.0, flutter_map_location_marker ^8.0.8 requires geolocator ^11.0.0.
So, because sona_app depends on both flutter_map_location_marker ^8.0.8 and geolocator ^12.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on geolocator: flutter pub add geolocator:^11.1.0
exit code 1

**Comment by tlserver** [comment]
v9.0.0 support geolocator v12 now.
