### ISSUE TITLE
Heading beacon not shown when app deployed as PWA on mobile.

### ISSUE THREAD

**Issue by kostaa** [tlserver/flutter_map_location_marker#134]
Just to add that the same app works fine when deployed as a native Android app.
I have added a compass to the widget and the compass works as expected.

A minimal reproducible app attached. See the readme.md for details.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Chrome - develop for the web
[√] IntelliJ IDEA Ultimate Edition (version 2024.2)
[√] Connected device (2 available)
[√] Network resources

Tested on Google Pixel 7 with Chrome browser 129.0.6668.100

[mra.zip](https://github.com/user-attachments/files/17399371/mra.zip)

![image](https://github.com/user-attachments/assets/ff1c46c5-576b-4239-aa3f-b963524af565)

**Comment by tlserver** [comment]
This is not a bug, it is expected. Compass is disabled for web environment since [flutter_compass](https://pub.dev/packages/flutter_compass), the default heading implementation, only support android and iOS.

To overcome this, you can switch to custom implementation or other library which support web platform heading by providing a [headingStream](https://pub.dev/documentation/flutter_map_location_marker/latest/flutter_map_location_marker/CurrentLocationLayer/headingStream.html) ,which is a `Stream<LocationMarkerHeading?>`.

**Comment by kostaa** [comment]
In other words, you're saying this library only supports iOS and Android platforms out of the box.

**Comment by kostaa** [comment]
If that is the case it would be good to make it obvious in the platform list (I was explicitly looking for a library that supports Web) 
![image](https://github.com/user-attachments/assets/a1b730b4-55c1-4982-bf1c-37486acb24bc)
