### ISSUE TITLE
Change request to followOnLocationUpdate 

### ISSUE THREAD

**Issue by dfrobese** [tlserver/flutter_map_location_marker#60]
Hi, can you make the mode editable without rebuilding the whole FlutterMap child stack? 

I want to switch between the modes without rebuilding always the child stack. The example 
follow_fab_example.dart is very resource consuming when you follow the approach in an real app.

**Comment by tlserver** [comment]
I don't think there is another way to handle map moving in flutter_map.🤔

**Comment by tlserver** [comment]
Ok, I see what you mean. I think the problem you meantioned is that every guesture cause the widget calling `setState()`. It can be solved by adding a check before calling `setState()`.

```dart
          // Stop following the location marker on the map if user interacted with the map.
          onPositionChanged: (MapPosition position, bool hasGesture) {
            if (hasGesture && _followOnLocationUpdate != FollowOnLocationUpdate.never) {
              setState(
                () => _followOnLocationUpdate = FollowOnLocationUpdate.never,
              );
            }
          },
```

I think it is overhead if `CurrentLocationLayer` use `Stream<FollowOnLocationUpdate>` to receive parameters because the frequency of changing `followOnLocationUpdate` is not high. But if you really care for that the whole map rebild which caused by updating `followOnLocationUpdate`, you can warp the CurrentLocationLayer in to a StreamBuilder and create a Stream<FollowOnLocationUpdate> yourself.
